### ISSUE TITLE
Encountered a fatal error.

### ISSUE THREAD

**Issue by heinnovator** [karpach/remote-controller#4]
Log file

2022-07-31 06:37:27.4683|FATAL|Karpach.Remote.Commander.Program|Autofac.Core.DependencyResolutionException: An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = ControllerApplicationContext (ReflectionActivator), Services = [Karpach.Remote.Commander.ControllerApplicationContext], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = OwnedByLifetimeScope ---> An exception was thrown while invoking the constructor 'Void .ctor(Factory, Factory, Karpach.Remote.Commander.Interfaces.ICommandsSettings, Factory)' on type 'ControllerApplicationContext'. ---> Cannot cast the underlying exported value of type 'Karpach.Remote.Commands.CommandsContainer (ContractName="Karpach.Remote.Commands.Interfaces.IRemoteCommandContainer")' to type 'Karpach.Remote.Commands.Interfaces.IRemoteCommandContainer'. (See inner exception for details.) (See inner exception for details.) ---> Autofac.Core.DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(Factory, Factory, Karpach.Remote.Commander.Interfaces.ICommandsSettings, Factory)' on type 'ControllerApplicationContext'. ---> Cannot cast the underlying exported value of type 'Karpach.Remote.Commands.CommandsContainer (ContractName="Karpach.Remote.Commands.Interfaces.IRemoteCommandContainer")' to type 'Karpach.Remote.Commands.Interfaces.IRemoteCommandContainer'. (See inner exception for details.) ---> System.ComponentModel.Composition.CompositionContractMismatchException: Cannot cast the underlying exported value of type 'Karpach.Remote.Commands.CommandsContainer (ContractName="Karpach.Remote.Commands.Interfaces.IRemoteCommandContainer")' to type 'Karpach.Remote.Commands.Interfaces.IRemoteCommandContainer'.
   at System.ComponentModel.Composition.ExportServices.CastExportedValue[T](ICompositionElement element, Object exportedValue)
   at System.ComponentModel.Composition.Hosting.ExportProvider.GetExportedValuesCore[T](String contractName)
   at Karpach.Remote.Commander.ControllerApplicationContext..ctor(Factory settingsFormFactory, Factory hostHelperFactory, ICommandsSettings commandsSettings, Factory commandManagerFactory) in C:\projects\remote-controller\Karpach.Remote.Commander\ControllerApplicationContext.cs:line 38
   at lambda_method(Closure , Object[] )
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   --- End of inner exception stack trace ---
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context, IEnumerable`1 parameters)
   at Karpach.Remote.Commander.Program.Main() in C:\projects\remote-controller\Karpach.Remote.Commander\Program.cs:line 32

**Comment by karpach** [comment]
I upgraded the project to .NET 6. Please try again, and see if it solves the problem.

**Comment by zomar** [comment]
Same problem
![image](https://user-images.githubusercontent.com/1669247/232110640-f142f6d5-5e02-4338-8f47-e8351db93df0.png)
`2023-04-14 10:01:23.2969|FATAL|Karpach.Remote.Commander.Program|Autofac.Core.DependencyResolutionException: An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = ControllerApplicationContext (ReflectionActivator), Services = [Karpach.Remote.Commander.ControllerApplicationContext], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = OwnedByLifetimeScope ---> An exception was thrown while invoking the constructor 'Void .ctor(Factory, Factory, Karpach.Remote.Commander.Interfaces.ICommandsSettings, Factory)' on type 'ControllerApplicationContext'. ---> Could not find a part of the path 'C:\Plugins'. (See inner exception for details.) (See inner exception for details.)
 ---> Autofac.Core.DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(Factory, Factory, Karpach.Remote.Commander.Interfaces.ICommandsSettings, Factory)' on type 'ControllerApplicationContext'. ---> Could not find a part of the path 'C:\Plugins'. (See inner exception for details.)
 ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Plugins'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at Karpach.Remote.Commander.ControllerApplicationContext..ctor(Factory settingsFormFactory, Factory hostHelperFactory, ICommandsSettings commandsSettings, Factory commandManagerFactory) in C:\projects\remote-controller\Karpach.Remote.Commander\ControllerApplicationContext.cs:line 25
   at lambda_method10(Closure , Object[] )
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   --- End of inner exception stack trace ---
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.ResolveOperation.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Container.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve(IComponentContext context, Type serviceType, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context)
   at Karpach.Remote.Commander.Program.Main() in C:\projects\remote-controller\Karpach.Remote.Commander\Program.cs:line 34
2023-04-14 10:01:53.3083|FATAL|Karpach.Remote.Commander.Program|Autofac.Core.DependencyResolutionException: An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = ControllerApplicationContext (ReflectionActivator), Services = [Karpach.Remote.Commander.ControllerApplicationContext], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = OwnedByLifetimeScope ---> An exception was thrown while invoking the constructor 'Void .ctor(Factory, Factory, Karpach.Remote.Commander.Interfaces.ICommandsSettings, Factory)' on type 'ControllerApplicationContext'. ---> Could not find a part of the path 'C:\Plugins'. (See inner exception for details.) (See inner exception for details.)
 ---> Autofac.Core.DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(Factory, Factory, Karpach.Remote.Commander.Interfaces.ICommandsSettings, Factory)' on type 'ControllerApplicationContext'. ---> Could not find a part of the path 'C:\Plugins'. (See inner exception for details.)
 ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Plugins'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at Karpach.Remote.Commander.ControllerApplicationContext..ctor(Factory settingsFormFactory, Factory hostHelperFactory, ICommandsSettings commandsSettings, Factory commandManagerFactory) in C:\projects\remote-controller\Karpach.Remote.Commander\ControllerApplicationContext.cs:line 25
   at lambda_method10(Closure , Object[] )
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   --- End of inner exception stack trace ---
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.ResolveOperation.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Container.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve(IComponentContext context, Type serviceType, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context)
   at Karpach.Remote.Commander.Program.Main() in C:\projects\remote-controller\Karpach.Remote.Commander\Program.cs:line 34
2023-04-14 10:03:43.0918|FATAL|Karpach.Remote.Commander.Program|Autofac.Core.DependencyResolutionException: An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = ControllerApplicationContext (ReflectionActivator), Services = [Karpach.Remote.Commander.ControllerApplicationContext], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = OwnedByLifetimeScope ---> An exception was thrown while invoking the constructor 'Void .ctor(Factory, Factory, Karpach.Remote.Commander.Interfaces.ICommandsSettings, Factory)' on type 'ControllerApplicationContext'. ---> Could not find a part of the path 'C:\Plugins'. (See inner exception for details.) (See inner exception for details.)
 ---> Autofac.Core.DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(Factory, Factory, Karpach.Remote.Commander.Interfaces.ICommandsSettings, Factory)' on type 'ControllerApplicationContext'. ---> Could not find a part of the path 'C:\Plugins'. (See inner exception for details.)
 ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Plugins'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at Karpach.Remote.Commander.ControllerApplicationContext..ctor(Factory settingsFormFactory, Factory hostHelperFactory, ICommandsSettings commandsSettings, Factory commandManagerFactory) in C:\projects\remote-controller\Karpach.Remote.Commander\ControllerApplicationContext.cs:line 25
   at lambda_method10(Closure , Object[] )
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   --- End of inner exception stack trace ---
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.ResolveOperation.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Container.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve(IComponentContext context, Type serviceType, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context)
   at Karpach.Remote.Commander.Program.Main() in C:\projects\remote-controller\Karpach.Remote.Commander\Program.cs:line 34
`

**Comment by gialla1987** [comment]
fatal error also for me, on win 10

remote-shutdown works fine instead

2023-06-23 01:34:03.0174|FATAL|Karpach.Remote.Commander.Program|Autofac.Core.DependencyResolutionException: An error occurred during the activation of a particular registration. See the inner exception for details. Registration: Activator = ControllerApplicationContext (ReflectionActivator), Services = [Karpach.Remote.Commander.ControllerApplicationContext], Lifetime = Autofac.Core.Lifetime.CurrentScopeLifetime, Sharing = None, Ownership = OwnedByLifetimeScope ---> An exception was thrown while invoking the constructor 'Void .ctor(Factory, Factory, Karpach.Remote.Commander.Interfaces.ICommandsSettings, Factory)' on type 'ControllerApplicationContext'. ---> Could not find a part of the path 'C:\Plugins'. (See inner exception for details.) (See inner exception for details.)
 ---> Autofac.Core.DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(Factory, Factory, Karpach.Remote.Commander.Interfaces.ICommandsSettings, Factory)' on type 'ControllerApplicationContext'. ---> Could not find a part of the path 'C:\Plugins'. (See inner exception for details.)
 ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Plugins'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at Karpach.Remote.Commander.ControllerApplicationContext..ctor(Factory settingsFormFactory, Factory hostHelperFactory, ICommandsSettings commandsSettings, Factory commandManagerFactory) in C:\projects\remote-controller\Karpach.Remote.Commander\ControllerApplicationContext.cs:line 25
   at lambda_method10(Closure , Object[] )
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   --- End of inner exception stack trace ---
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.ResolveOperation.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Container.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve(IComponentContext context, Type serviceType, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context)
   at Karpach.Remote.Commander.Program.Main() in C:\projects\remote-controller\Karpach.Remote.Commander\Program.cs:line 34

**Comment by Pattern91** [comment]
i got the same error. Also Win10, latest updates. Runtime 6.0 is installed

**Comment by karpach** [comment]
I finally found time to troubleshoot the problem. The problem was related to the creation of the release package, the actual source code was building and running fine.

I just fixed it in [remote-controller-v1.1.64](https://github.com/karpach/remote-controller/releases/tag/v1.1.64).
